= Transform Path Policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-transform-path/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-transform-path/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]


== Phase

[cols="2*", options="header"]
|===
^|onRequest
^|onResponse

^.^| X
^.^|

|===


== Description
The transform path policy is used to alter the path in a request without affecting the endpoint selection.


== Attributes

|===
|Name |Description

|===


== Configuration
When using the Dynamic Routing policy, you can define multiple path changes and their respective redirections according to the
initial request path.

WARNING: When defining a path change, please consider that the API's context-path must not be part of the rule's path!
If your context-path is `/myapi` and your call is `/myapi/123`, if you want to select `123` the regular expression will be `/(.*)`.
Don't forget the `/`.

Also note that the result of the policy should be a path, NOT a URL.

=== Regular expressions
Rules can be defined using regular expression: `/v1/stores/(.*)`.

Using regular expressions can be very useful when you want to capture some parts of the initial request path and reuse
them to define the redirection.

For example: the rule's path is `/v1/stores/(.*)` to capture the end of the path after `/v1/stores/` and use it
in the _redirect to_ property: `\http://store_backend/stores/{#group[0]}`

An other great feature is the possibility to use named group instead of indexed group.
`/api/(?<version>v[0-9]+)/stores.*` => `\http://host1/products/api/{#groupName['version']}`

[source, json]
.Configuration example
----
"dynamic-routing": {
    "rules": [
        {
            "pattern": "/v1/stores/(.*)",
            "url": "http://host2/stores/{#group[0]}"
        }
    ]
}
----


== Http Status Code
|===
|Code |Message

.^| ```400```
| When no rule match the inbound request

|===
